### ISSUE TITLE
User Story 1: List of all Art Pieces

### ISSUE THREAD

**Issue by P-Oliomonte** [P-Oliomonte/Art-Gallery#1]
#### Value Proposition

**As an** art enthusiast

**I want to** see a list of all art pieces

**so that** I can get an overview of all art pieces.

#### Acceptance Criteria

- [ ] All art pieces are displayed as a list
- [ ] Each art piece's image is displayed
- [ ] Each art piece's title is displayed
- [ ] Each art piece's artist is displayed

#### Tasks

- [ ] Fetch all art pieces with `SWR` in `pages/index.js`
- [ ] Create the component `ArtPieces` to render a list
- [ ] `ArtPieces` props: `pieces`
- [ ] Create the component `ArtPiecePreview`
- [ ] `ArtPiecePreview` props: `image`, `title`, `artist`
