### ISSUE TITLE
User Story 5: Favorites

### ISSUE THREAD

**Issue by P-Oliomonte** [P-Oliomonte/Art-Gallery#5]
#### Value Proposition

**As an** art enthusiast

**I want to** mark art piece pieces as favorites

**so that** I can find them easier.

#### Acceptance Criteria

- [ ] The favorite-button is displayed in each entry in the list view
- [ ] The favorite-button is displayed in the details view
- [ ] The favorite-button is NOT displayed in the spotlight view
- [ ] Clicking the favorite-button on a non-favorite piece saves it as a favorite
- [ ] Clicking the favorite-button on a favorite piece removes it from favorites

#### Tasks

- [ ] Create an additional state `artPiecesInfo` to save further information for art pieces
- [ ] Make the `artPiecesInfo` state globally available for all pages
- [ ] Store the favorite flag in the `artPiecesInfo`
- [ ] Reference art pieces by `slug` in the additional state
- [ ] Create the component `FavoriteButton`
- [ ] `FavoriteButton` props: `isFavorite`, `onToggleFavorite`
- [ ] Render the `FavoriteButton` component in the `Spotlight`, `ArtPiecePreview` and `ArtPieceDetails` component
