### ISSUE TITLE
User Story 8: Persist Favorites and Comments in the Browser

### ISSUE THREAD

**Issue by P-Oliomonte** [P-Oliomonte/Art-Gallery#8]
#### Value Proposition

**As an** art enthusiast

**I want to** persist my favorites and comments

**so that** the data will not be lost when I close the app.

#### Acceptance Criteria

- [ ] All favorite flags and comments added to art pieces are persisted across browser reloads

#### Tasks

- [ ] Install the package `use-local-storage-state`
- [ ] Use the `useLocalStorageState` hook to store the `artPiecesInfo` state
